version: '3'

services:
    db-sms:
        image: postgres:9.6.17
        container_name: 'db-sms'
        environment:
            - POSTGRES_DB=sca_sms
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=paj45TFcli
        volumes:
            - '../../data/postgres:/var/lib/postgresql/data'
        ports:
            - 5431:5432
        restart: unless-stopped

    api-sms:
        image: api-sms
        container_name: api-sms
        build:
            context: ../../
            dockerfile: docker/laravel/Dockerfile
        volumes:
            - ../../:/var/www/
        environment:
            - APP_NAME=SCA-SMS
            - DB_CONNECTION=sca_sms
            - DB_HOST=db-sms
            - DB_PORT=5432
            - DB_DATABASE=sca_sms
            - DB_USERNAME=postgres
            - DB_PASSWORD=paj45TFcli
        depends_on:
            - db-sms
        restart: unless-stopped

    queue-sms:
        image: queue-sms
        container_name: queue-sms
        build:
            context: ../../
            dockerfile: docker/laravel/Dockerfile
        volumes:
            - ../../:/var/www/
        command: /bin/sh -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/laravel-worker.conf"
        environment:
            - APP_NAME=SCA-SMS
            - DB_CONNECTION=sca_sms
            - DB_HOST=db-sms
            - DB_PORT=5432
            - DB_DATABASE=sca_sms
            - DB_USERNAME=postgres
            - DB_PASSWORD=paj45TFcli
        depends_on:
            - db-sms
        restart: unless-stopped

    nginx-sms:
        image: nginx-sms
        container_name: nginx-sms
        build:
            context: ../../
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ../../:/var/www
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../nginx/sites/:/etc/nginx/sites-available
            - ../nginx/conf.d/:/etc/nginx/conf.d
        depends_on: 
            - api-sms
        ports:
            - 80:80
        restart: unless-stopped
