version: '3'

services:
    wallet-db:
      image: mysql
      container_name: wallet-db
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: wallet
        MYSQL_USER: wallet
        MYSQL_PASSWORD: "Q%XY2r9AN+!8"
        MYSQL_ROOT_PASSWORD: "Q%XY2r9AN+!8"

    wallet-api:
        image: wallet-api
        container_name: wallet-api
        build:
            context: ../../
            dockerfile: docker/php/Dockerfile
        environment:
            - APP_ENV=production
        depends_on:
            - wallet-db
        restart: unless-stopped

    walllet-queue:
        image: wallet-queue
        container_name: wallet-queue
        build:
            context: ../../
            dockerfile: docker/php/Dockerfile
        command: /bin/sh -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/laravel-worker.conf"
        environment:
            - APP_ENV=production
        depends_on:
            - wallet-db
        restart: unless-stopped

    wallet-nginx:
        image: wallet-nginx
        container_name: wallet-nginx
        build:
            context: ../../
            dockerfile: docker/nginx/Dockerfile
        environment:
            - APP_ENV=production
        depends_on:
            - wallet-api
        ports:
            - 8000:80
        restart: unless-stopped
